spring:
  application:
    name: microservice-reloj
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db4:3309/bd4
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        '[globally_quoted_identifiers]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
server:
  port: 8092
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}