spring:
  application:
    name: microservice-sueldo
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-db5:3306/bd5
    username: root
    password: 123456
  jpa:
    properties:
      hibernate:
        '[globally_quoted_identifiers]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
server:
  port: 8094
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance: 
    instance: ${spring.application.name}:${spring.application.instance_id:${random.value}}
management:
  endpoints:
    web:
      exposure:
        include: '*'