spring:
  application:
    name: microservice-solicitud
  datasource:
    url: jdbc:mysql://localhost:3306/solicitudes
    username: root
    password: Chile&2022
  jpa:
    properties:
      hibernate:
        '[globally_quoted_identifiers]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
server:
  port: 8093
  forward-headers-strategy: framework
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}