spring:
  application:
    name: microservice-justificativo
  datasource:
    url: jdbc:mysql://localhost:3306/justificativos
    username: root
    password: Chile&2022
  jpa:
    properties:
      hibernate:
        '[globally_quoted_identifiers]': true
        jdbc:
          lob:
            '[non_contextual_creation]': true
    hibernate:
      use-new-id-generator-mappings: false
      ddl-auto: create-drop
server:
  port: 8091
  forward-headers-strategy: framework
keycloak:
  realm: MueblesStgo
  auth-server-url: http://localhost:8080
  resource: mueblesStgo-keycloak
  public-client: true
  bearer-only: true
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}